// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentApi;

namespace StudentApi.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentApi.Models.Classroom", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityID");

                    b.ToTable("Classroom");

                    b.HasData(
                        new
                        {
                            EntityID = 1L,
                            ClassCode = "COM101"
                        },
                        new
                        {
                            EntityID = 2L,
                            ClassCode = "COM201"
                        },
                        new
                        {
                            EntityID = 3L,
                            ClassCode = "ENG101"
                        },
                        new
                        {
                            EntityID = 4L,
                            ClassCode = "CHI101"
                        },
                        new
                        {
                            EntityID = 5L,
                            ClassCode = "MAT101"
                        },
                        new
                        {
                            EntityID = 6L,
                            ClassCode = "MAT201"
                        });
                });

            modelBuilder.Entity("StudentApi.Models.Student", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Age")
                        .HasColumnType("smallint");

                    b.Property<long?>("ClassroomEntityID")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityID");

                    b.HasIndex("ClassroomEntityID");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            EntityID = 1L,
                            Age = (short)16,
                            FirstName = "Moka",
                            LastName = "Mogami"
                        },
                        new
                        {
                            EntityID = 2L,
                            Age = (short)17,
                            FirstName = "Mary",
                            LastName = "Jane"
                        },
                        new
                        {
                            EntityID = 3L,
                            Age = (short)18,
                            FirstName = "Michael",
                            LastName = "Vodka"
                        });
                });

            modelBuilder.Entity("StudentApi.Models.Student", b =>
                {
                    b.HasOne("StudentApi.Models.Classroom", null)
                        .WithMany("Students")
                        .HasForeignKey("ClassroomEntityID");
                });

            modelBuilder.Entity("StudentApi.Models.Classroom", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
